### ISSUE TITLE
Should only respond to alphabetic characters

### ISSUE THREAD

**Issue by nadeemabdulhamid** [berry-cs/csc121-project-amelie-savannah#1]
While playing the game, it should only react to letters (not numbers or other symbols/keys) being pressed.

<img width="404" alt="Screenshot 2023-10-12 at 3 02 29 PM" src="https://github.com/berry-cs/csc121-project-amelie-savannah/assets/222592/eec97bef-183a-45bd-9e69-27cc0a877bac">

**Comment by awillett1** [comment]
See most recent file version.
